USE master
GO
IF EXISTS(SELECT * FROM sys.databases WHERE name='DVDLibrary')
DROP DATABASE DVDLibrary
GO

CREATE DATABASE DVDLibrary
GO

USE DVDLibrary
GO

CREATE TABLE DVDs
(
	DVDID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Title NVARCHAR(MAX),
	ReleaseYear NVARCHAR(MAX),
	Director NVARCHAR(MAX),
	Rating NVARCHAR(MAX),
	Notes NVARCHAR(MAX)
)